//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.05 at 10:52:28 AM IST 
//



package com.ericsson.fdp.http.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="msisdn" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="applicationResponse" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="appDrivenMenuCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="freeflow">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="freeflowState" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="freeflowCharging" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="freeflowChargingAmount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="parameters" type="{}parametersType" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "msisdn",
    "applicationResponse",
    "appDrivenMenuCode",
    "freeflow"
})
@XmlRootElement(name = "response")
public class Response {

    @XmlElement(required = true)
    protected String msisdn;
    @XmlElement(required = true)
    protected String applicationResponse;
    protected String appDrivenMenuCode;
    @XmlElement(required = true)
    protected Response.Freeflow freeflow;

    /**
     * Gets the value of the msisdn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMsisdn() {
        return msisdn;
    }

    /**
     * Sets the value of the msisdn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMsisdn(String value) {
        this.msisdn = value;
    }

    /**
     * Gets the value of the applicationResponse property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApplicationResponse() {
        return applicationResponse;
    }

    /**
     * Sets the value of the applicationResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApplicationResponse(String value) {
        this.applicationResponse = value;
    }

    /**
     * Gets the value of the appDrivenMenuCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAppDrivenMenuCode() {
        return appDrivenMenuCode;
    }

    /**
     * Sets the value of the appDrivenMenuCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAppDrivenMenuCode(String value) {
        this.appDrivenMenuCode = value;
    }

    /**
     * Gets the value of the freeflow property.
     * 
     * @return
     *     possible object is
     *     {@link Response.Freeflow }
     *     
     */
    public Response.Freeflow getFreeflow() {
        return freeflow;
    }

    /**
     * Sets the value of the freeflow property.
     * 
     * @param value
     *     allowed object is
     *     {@link Response.Freeflow }
     *     
     */
    public void setFreeflow(Response.Freeflow value) {
        this.freeflow = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="freeflowState" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="freeflowCharging" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="freeflowChargingAmount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="parameters" type="{}parametersType" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "freeflowState",
        "freeflowCharging",
        "freeflowChargingAmount",
        "parameters"
    })
    public static class Freeflow {

        @XmlElement(required = true)
        protected String freeflowState;
        protected String freeflowCharging;
        protected String freeflowChargingAmount;
        protected ParametersType parameters;

        /**
         * Gets the value of the freeflowState property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFreeflowState() {
            return freeflowState;
        }

        /**
         * Sets the value of the freeflowState property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFreeflowState(String value) {
            this.freeflowState = value;
        }

        /**
         * Gets the value of the freeflowCharging property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFreeflowCharging() {
            return freeflowCharging;
        }

        /**
         * Sets the value of the freeflowCharging property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFreeflowCharging(String value) {
            this.freeflowCharging = value;
        }

        /**
         * Gets the value of the freeflowChargingAmount property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFreeflowChargingAmount() {
            return freeflowChargingAmount;
        }

        /**
         * Sets the value of the freeflowChargingAmount property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFreeflowChargingAmount(String value) {
            this.freeflowChargingAmount = value;
        }

        /**
         * Gets the value of the parameters property.
         * 
         * @return
         *     possible object is
         *     {@link ParametersType }
         *     
         */
        public ParametersType getParameters() {
            return parameters;
        }

        /**
         * Sets the value of the parameters property.
         * 
         * @param value
         *     allowed object is
         *     {@link ParametersType }
         *     
         */
        public void setParameters(ParametersType value) {
            this.parameters = value;
        }

    }

}
