
package com.mtn.esf.xmlns.wsdl.updatecustomerdetails;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "UpdateCustomerDetailsService", targetNamespace = "http://xmlns.esf.mtn.com/wsdl/UpdateCustomerDetails", wsdlLocation = "file:/C:/MTNProject/ESFServiceContracts/ServiceContracts/UpdateCustomerDetails/UpdateCustomerDetails_v1.wsdl")
public class UpdateCustomerDetailsService
    extends Service
{

    private final static URL UPDATECUSTOMERDETAILSSERVICE_WSDL_LOCATION;
    private final static WebServiceException UPDATECUSTOMERDETAILSSERVICE_EXCEPTION;
    private final static QName UPDATECUSTOMERDETAILSSERVICE_QNAME = new QName("http://xmlns.esf.mtn.com/wsdl/UpdateCustomerDetails", "UpdateCustomerDetailsService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/MTNProject/ESFServiceContracts/ServiceContracts/UpdateCustomerDetails/UpdateCustomerDetails_v1.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        UPDATECUSTOMERDETAILSSERVICE_WSDL_LOCATION = url;
        UPDATECUSTOMERDETAILSSERVICE_EXCEPTION = e;
    }

    public UpdateCustomerDetailsService() {
        super(__getWsdlLocation(), UPDATECUSTOMERDETAILSSERVICE_QNAME);
    }

    public UpdateCustomerDetailsService(WebServiceFeature... features) {
        super(__getWsdlLocation(), UPDATECUSTOMERDETAILSSERVICE_QNAME, features);
    }

    public UpdateCustomerDetailsService(URL wsdlLocation) {
        super(wsdlLocation, UPDATECUSTOMERDETAILSSERVICE_QNAME);
    }

    public UpdateCustomerDetailsService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, UPDATECUSTOMERDETAILSSERVICE_QNAME, features);
    }

    public UpdateCustomerDetailsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UpdateCustomerDetailsService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns UpdateCustomerDetailsPortType
     */
    @WebEndpoint(name = "UpdateCustomerDetailsPort")
    public UpdateCustomerDetailsPortType getUpdateCustomerDetailsPort() {
        return super.getPort(new QName("http://xmlns.esf.mtn.com/wsdl/UpdateCustomerDetails", "UpdateCustomerDetailsPort"), UpdateCustomerDetailsPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UpdateCustomerDetailsPortType
     */
    @WebEndpoint(name = "UpdateCustomerDetailsPort")
    public UpdateCustomerDetailsPortType getUpdateCustomerDetailsPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.esf.mtn.com/wsdl/UpdateCustomerDetails", "UpdateCustomerDetailsPort"), UpdateCustomerDetailsPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (UPDATECUSTOMERDETAILSSERVICE_EXCEPTION!= null) {
            throw UPDATECUSTOMERDETAILSSERVICE_EXCEPTION;
        }
        return UPDATECUSTOMERDETAILSSERVICE_WSDL_LOCATION;
    }

}
