package com.ericsson.fdp.business.enums.ivr;

public enum IVRResponseTypes {

	RECURRING_SERVICE_SUCCESS_RESPONSE,
	
	RECURRING_SERVICE_FAIL_RESPONSE,
	
	TARIFF_SUCCESS_RESPONSE,
	
	BALANCE_ENQUIRY_SUCCESS_RESPONSE,
	
	PRODUCT_BUY_SUCCESS_RESPONSE,
	
	COMMAND_SUCCESS_RESPONSE,
	
	FULFILLMENT_FAIL_RESPONSE,
	
	ADD_SHARED_CONSUMER_SUCCESS_RESPONSE,
	
	REMOVE_SHARED_CONSUMER_SUCCESS_RESPONSE,
	
	VIEW_ALL_SHARED_CONSUMER_SUCCESS_RESPONSE,
	
	VIEW_SHARED_USAGE_CONSUMER_SUCCESS_RESPONSE,
	
	ACCEPT_SHARED_CONSUMER_SUCCESS_RESPONSE,
	
	VIEW_ALL_SHARED_PROVIDER_SUCCESS_RESPONSE,
	
	PRODUCT_BUY_FAIL_RESPONSE,
	
	OFFLINE_NOTIFICAITON_SUCESS_RESPONSE,
	
	VIEW_HISTORY,
	
	OPT_IN_SUCCESS_RESPONSE,
	
	OPT_OUT_SUCCESS_RESPONSE,
	
	OPT_IN_FAILURE_RESPONSE,
	
	OPT_OUT_FAILURE_RESPONSE,
	
	BUNDLE_PRICE_SUCCESS_RESPONSE,
	
	BUNDLE_PRICE_FAILURE_RESPONSE,
	
	VIEW_SUBS_HISTORY_SUCCESS_RESPONSE,
	
	VIEW_SUBS_HISTORY_FAILURE_RESPONSE,
	
	FAF_SUCCESS_RESPONSE,
	
	FAF_FAILURE_RESPONSE,
	
	ME2ULIST_SUCCESS_RESPONSE, 
	
	TIME2SHARE_SUCCESS_RESPONSE, 
	
	TIME2SHARE_FAILURE_RESPONSE,
	
	ABILITY_SUCCESS_RESPONSE,
	
	SIM_CHANGE_SUCCESS_RESPONSE, 
	
	SIM_CHANGE_FAILURE_RESPONSE,
	
	DEVICE_CHANGE_SUCCESS_RESPONSE,
	
	DEVICE_CHANGE_FAILURE_RESPONSE,
	
	/** The VIEW_ACTIVE_BUNDLES_SUCCESS_RESPONSE Constant */
	VIEW_ACTIVE_BUNDLES_SUCCESS_RESPONSE,
	/** The VIEW_ACTIVE_BUNDLES_FAILURE_RESPONSE Constant */
	VIEW_ACTIVE_BUNDLES_FAILURE_RESPONSE
	;
	
}
