package com.ericsson.fdp.business.enums;

/**
 * The Enum ConfigurationKey.
 */
public enum ConfigurationKey {

	/** The originhostname. */
	ORIGINHOSTNAME("originHostName"),

	/** The originnodetype. */
	ORIGINNODETYPE("originNodeType"),

	/** The msisdn number length. */
	MSISDN_NUMBER_LENGTH("MSISDN_NUMBER_LEN"),

	/** The country code. */
	COUNTRY_CODE("COUNTRY_CODE"),

	/** The whitelisted number testing. */
	WHITELISTED_NUMBER_TESTING("WHITELISTED_NUMBER_TESTING"),

	/** The otp deletion time minutes. */
	OTP_DELETION_TIME_MINUTES("OTP_DELETION_TIME_MINUTES"),

	/** The delete shared account expired request leased time. */
	DELETE_SHARED_ACCOUNT_EXPIRED_REQUEST_LEASED_TIME("DeleteSharedAccountExpiredRequestLeasedTimeMinutes"),

	/**
	 * The sms delay time.
	 */
	SMS_DELAY_TIME("SMS_DELAY_TIME"),

	/**
	 * The valid responses for product buy.
	 */
	PRODUCT_BUY_VALID_RESPONSES("PRODUCT_BUY_VALID_RESPONSES"),

	/**
	 * The valid responses for product buy.
	 */
	PRODUCT_BUY_VALID_RESPONSES_FOR_COD("PRODUCT_BUY_VALID_RESPONSES_FOR_COD"),
	/**
	 * The invalid input string.
	 */
	INVALID_INPUT_STRING("INVALID_INPUT_STRING"),

	/**
	 * The more code for ussd channel.
	 */
	MORE_CODE_FOR_USSD("MORE_CODE_FOR_USSD"),

	/**
	 * The previous code for ussd.
	 */
	PREV_CODE_FOR_USSD("PREV_CODE_FOR_USSD"),

	/**
	 * The main menu code for ussd.
	 */
	MAIN_MENU_CODE_FOR_USSD("MAIN_MENU_CODE_FOR_USSD"),

	/**
	 * The previous menu code for ussd.
	 */
	PREV_MENU_CODE_FOR_USSD("PREV_MENU_CODE_FOR_USSD"),

	/**
	 * The exit code for ussd.
	 */
	EXIT_CODE_FOR_USSD("EXIT_CODE_FOR_USSD"),

	/**
	 * The more code for sms.
	 */
	MORE_CODE_FOR_SMS("MORE_CODE_FOR_SMS"),

	/**
	 * The previous code for sms.
	 */
	PREV_CODE_FOR_SMS("PREV_CODE_FOR_SMS"),

	/**
	 * The main menu code for sms.
	 */
	MAIN_MENU_CODE_FOR_SMS("MAIN_MENU_CODE_FOR_SMS"),

	/**
	 * The previous menu code for sms.
	 */
	PREV_MENU_CODE_FOR_SMS("PREV_MENU_CODE_FOR_SMS"),

	/**
	 * The exit code for sms.
	 */
	EXIT_CODE_FOR_SMS("EXIT_CODE_FOR_SMS"),

	/**
	 * The footer code text seperator.
	 */
	FOOTER_CODE_TEXT_SEPERATOR("FOOTER_CODE_TEXT_SEPERATOR"),

	/**
	 * The footer options seperator.
	 */
	FOOTER_OPTIONS_SEPERATOR("FOOTER_OPTIONS_SEPERATOR"),
	/**
	 * The previous menu text for ussd.
	 */
	PREV_MENU_TEXT_FOR_USSD("PREV_MENU_TEXT_FOR_USSD"),
	/**
	 * The previous menu text for sms.
	 */
	PREV_MENU_TEXT_FOR_SMS("PREV_MENU_TEXT_FOR_SMS"),
	/**
	 * The main menu text for ussd.
	 */
	MAIN_MENU_TEXT_FOR_USSD("MAIN_MENU_TEXT_FOR_USSD"), /**
	 * The main menu text
	 * for sms.
	 */
	MAIN_MENU_TEXT_FOR_SMS("MAIN_MENU_TEXT_FOR_SMS"), /**
	 * The exit text for ussd.
	 */
	EXIT_TEXT_FOR_USSD("EXIT_TEXT_FOR_USSD"), /**
	 * The exit text for sms.
	 */
	EXIT_TEXT_FOR_SMS("EXIT_TEXT_FOR_SMS"), /**
	 * The more text for ussd.
	 */
	MORE_TEXT_FOR_USSD("MORE_TEXT_FOR_USSD"), /**
	 * The more text for sms.
	 */
	MORE_TEXT_FOR_SMS("MORE_TEXT_FOR_SMS"), /**
	 * The previous text for ussd.
	 */
	PREV_TEXT_FOR_USSD("PREV_TEXT_FOR_USSD"), /**
	 * The previous text for sms.
	 */
	PREV_TEXT_FOR_SMS("PREV_TEXT_FOR_SMS"),
	/**
	 * The exit response.
	 */
	EXIT_RESPONSE("EXIT_RESPONSE"),
	/**
	 * For error code 100.
	 */
	TIME_OFFSET_FOR_ERROR100("TIME_OFFSET_FOR_ERROR100"),
	/**
	 * 
	 * The flash delay for ussd.
	 */
	FLASH_DELAY_FOR_USSD("FLASH_DELAY_FOR_USSD"),
	/**
	 * The number of times product retry will be done.
	 */
	PRODUCT_RETRY_NUMBER("PRODUCT_RETRY_NUMBER"),

	/**
	 * product buy invalid responses.
	 */
	PRODUCT_BUY_INVALID_RESPONSES("PRODUCT_BUY_INVALID_RESPONSES"),

	/**
	 * Apply Coupon choice on Product Buy
	 */
	PRODUCT_BUY_APPLY_COUPON_CHOICE("PRODUCT_BUY_APPLY_COUPON_CHOICE"),

	/**
	 * Text To display if user have coupons.
	 */
	PRODUCT_BUY_APPLY_COUPON_CHOICE_TEXT("PRODUCT_BUY_APPLY_COUPON_CHOICE_TEXT"),

	/**
	 * The threeG activation mode.
	 */
	THREEG_ACTIVATION_MODE("THREEG_ACTIVATION_MODE"),
	/**
	 * The ICR circle.
	 */
	ICR_CIRCLE("ICR_CIRCLE"),
	/**
	 * The EQOSID.
	 */
	EQOSID("EQOSID"),
	/**
	 * The APNID.
	 */
	APNID("APNID"),
	/**
	 * The APNID.
	 */
	PDPID("PDPID"),

	PRODUCT_DATABASE_SAVE_REQ_SMS("PRODUCT_DATABASE_SAVE_REQ_SMS"),

	PRODUCT_DATABASE_SAVE_REQ_USSD("PRODUCT_DATABASE_SAVE_REQ_USSD"),

	PRODUCT_DATABASE_SAVE_REQ_WEB("PRODUCT_DATABASE_SAVE_REQ_WEB"),
	/**
	 * The sc default name.
	 */
	SC_DEFAULT_NAME("SC_DEFAULT_NAME"),

	/**
	 * The validity format to be send in tariff notification
	 */
	TARIFF_VALIDITY_FORMAT("TARIFF_VALIDITY_FORMAT"),

	/**
	 * The Tariff Enquiry Unit conversion.
	 */
	TARIFF_ENQUIRY_UNIT_CONVERSION_ALLOW("TARIFF_ENQUIRY_UNIT_CONVERSION_ALLOW"),

	/**
	 * The Tariff Enquiry Unit conversion.
	 */
	REJECTED_INPUT_STRING("REJECTED_INPUT_STRING"),

	/** The NOTIFICATION_POSTPAID_CONSUMER_ERROR_CODE_USSD */
	NOTIFICATION_POSTPAID_CONSUMER_ERROR_CODE_USSD("NOTIFICATION_POSTPAID_CONSUMER_ERROR_CODE_USSD"),

	/** The NOTIFICATION_POSTPAID_CONSUMER_ERROR_CODE_SMS */
	NOTIFICATION_POSTPAID_CONSUMER_ERROR_CODE_SMS("NOTIFICATION_POSTPAID_CONSUMER_ERROR_CODE_SMS"),

	/** The NOTIFICATION_PAM_NOT_CONFIGURED_TEXT */
	NOTIFICATION_PAM_NOT_CONFIGURED_TEXT("NOTIFICATION_PAM_NOT_CONFIGURED_TEXT"),

	/** The MANHATTAN_REQUEST_CIRCLEID */
	MANHATTAN_REQUEST_CIRCLEID("MANHATTAN_REQUEST_CIRCLEID"),

	/** The MANHATTAN_FAIL_DEFAULT_NOTIFICATION_TEXT */
	MANHATTAN_FAIL_DEFAULT_NOTIFICATION_TEXT("MANHATTAN_FAIL_DEFAULT_NOTIFICATION_TEXT"),

	/** The TARIFF_ENQUIRY_VALUE_CONVERSION_ALLOWED_CHANNELS **/
	TARIFF_ENQUIRY_VALUE_CONVERSION_ALLOWED_CHANNELS("TARIFF_ENQUIRY_VALUE_CONVERSION_ALLOWED_CHANNELS"),

	COUPON_CONF_TEXT_FOR_EXTRA_BENEFIT_ABSAMT("COUPON_CONF_TEXT_FOR_EXTRA_BENEFIT_ABSAMT"),

	COUPON_CONF_TEXT_FOR_EXTRA_BENEFIT_PERCAMT("COUPON_CONF_TEXT_FOR_EXTRA_BENEFIT_PERCAMT"),

	COUPON_CONF_TEXT_FOR_MRPDIS_ABSAMT("COUPON_CONF_TEXT_FOR_MRPDIS_ABSAMT"),

	COUPON_CONF_TEXT_FOR_MRPDIS_PERCAMT("COUPON_CONF_TEXT_FOR_MRPDIS_PERCAMT"),

	EXTERNAL_DATA_FEILD_DEFAULT_VALUE("EXTERNAL_DATA_DEFAULT_VALUE"),

	/** this amount should be left after loan and product buy with loan */
	MIN_BALANCE_POST_LOAN("MIN_BALANCE_POST_LOAN"),

	/**
	 * this is used to send cod fail sms from fdp online which is coming from
	 * COD system
	 */
	SMS_FAIL_NOTIFICATION_COD("SMS_FAIL_NOTIFICATION_COD"),

	/** The Constant NOTIFICATION_POSTPAID_CONSUMER_ERROR_CODE_IVR **/
	NOTIFICATION_POSTPAID_CONSUMER_ERROR_CODE_IVR("NOTIFICATION_POSTPAID_CONSUMER_ERROR_CODE_IVR"),

	/** The Constant POSTPAID_SERVICE_CLASS **/
	POSTPAID_SERVICE_CLASS("POSTPAID_SERVICE_CLASS"),

	/** The Constant IS_IVR_WEB_CHECK_FOR_PRE_POST_CONSUMER_ALLOWED **/
	IS_IVR_WEB_CHECK_FOR_PRE_POST_CONSUMER_ALLOWED("IS_IVR_WEB_CHECK_FOR_PRE_POST_CONSUMER_ALLOWED"),

	/** The Constant BUY_OTHER_CHOICE_VALID_RESPONSES **/
	BUY_OTHER_CHOICE_VALID_RESPONSES("BUY_OTHER_CHOICE_VALID_RESPONSES"),

	/** The Constant BUY_SELF_CHOICE_VALID_RESPONSES **/
	BUY_SELF_CHOICE_VALID_RESPONSES("BUY_SELF_CHOICE_VALID_RESPONSES"),

	/** The Constant BUY_OTHER_CHOICE_TEXT **/
	BUY_OTHER_CHOICE_TEXT("BUY_OTHER_CHOICE_TEXT"),

	/** The Constant BUY_OTHER_MSISDN_TEXT **/
	BUY_OTHER_MSISDN_TEXT("BUY_OTHER_MSISDN_TEXT"),

	/** The Constant PAYMENT_CHOICE_TEXT **/
	PAYMENT_CHOICE_TEXT("PAYMENT_CHOICE_TEXT"),

	/** The Constant AIR_DISPLAY_TEXT **/
	AIR_DISPLAY_TEXT("AIR_DISPLAY_TEXT"),

	/** The Constant MOBILE_MONEY_DISPLAY_TEXT **/
	MOBILE_MONEY_DISPLAY_TEXT("MOBILE_MONEY_DISPLAY_TEXT"),

	/** The Constant LOYALITY_DISPLAY_TEXT **/
	LOYALITY_DISPLAY_TEXT("LOYALITY_DISPLAY_TEXT"),

	/** The Constant EVDS_DISPLAY_TEXT **/
	EVDS_DISPLAY_TEXT("EVDS_DISPLAY_TEXT"),

	SPLIT_TYPE_TEXT("SPLIT_TYPE_TEXT"),

	SPLIT_MIN("SPLIT_MIN"),

	SPLIT_MAX("SPLIT_MAX"),

	DEPROVISION_MENU("DEPROVISION_MENU"),

	/** Balance check expiry date format */
	BALANCE_CHECK_DATE_FORMAT("BALANCE_CHECK_DATE_FORMAT"),

	FAF_INDICATOR_ONNET("FAF_INDICATOR_ONNET"),

	FAF_INDICATOR_OFFNET("FAF_INDICATOR_OFFNET"),

	FAF_INDICATOR_INTERNATIONAL("FAF_INDICATOR_INTERNATIONAL"),

	FAF_CHARGING_TYPE("FAF_CHARGING_TYPE"),

	FAF_CHARGING_INDICATOR("FAF_CHARGING_INDICATOR"),

	/** Level 6 Menu **/
	DATA2SHARE_LEVEL6("DATA2SHARE_LEVEL6"),

	ADD_FAF_LOCAL_VALID_RESPONSES("ADD_FAF_LOCAL_VALID_RESPONSES"),

	ADD_FAF_INTERNATIONAL_VALID_RESPONSES("ADD_FAF_INTERNATIONAL_VALID_RESPONSES"),

	ADD_FNF_LOCAL_NUMBER_INPUT("ADD_FNF_LOCAL_NUMBER_INPUT"),

	ADD_FNF_INTERNATIONAL_NUMBER_INPUT("ADD_FNF_INTERNATIONAL_NUMBER_INPUT"),

	PRESS_1_CONFIRMATION("PRESS_1_CONFIRMATION"),

	ADD_FNF_CONFIRMATION_TEXT("ADD_FNF_CONFIRMATION_TEXT"),

	AMOUNT_FAF_ADD_LOCAL("AMOUNT_FAF_ADD_LOCAL"),

	AMOUNT_FAF_ADD_INTERNATIONAL("AMOUNT_FAF_ADD_INTERNATIONAL"), 
	
	ADD_FNF_DISPLAY_TEXT("ADD_FNF_DISPLAY_TEXT"),
	
	VIEW_FNF_LIST_TEXT("VIEW_FNF_LIST_TEXT"),
	
	FAF_LIST_IS_EMPTY("FAF_LIST_IS_EMPTY"),
	
	YOU_HAVE_SELECTED("YOU_HAVE_SELECTED"), 
	
	PRESS_1_CONFIRMATION_TEXT("PRESS_1_CONFIRMATION_TEXT"), 
	
	TO_DELETE("TO_DELETE"),
	
	TO_MODIFY("TO_MODIFY"),
	
	TIME2SHARE_ENABLED_ACCOUNTS("TIME2SHARE_ENABLED_ACCOUNTS"),
	
	TIME2SHARE_AMT_TO_SHARE_TEXT1("TIME2SHARE_AMT_TO_SHARE_TEXT1"),
	
	TIME2SHARE_AMT_TO_SHARE_TEXT2("TIME2SHARE_AMT_TO_SHARE_TEXT2"),
	
	ME2U_ENTER_BENEFICIARY_MSISDN_TEXT("ME2U_ENTER_BENEFICIARY_MSISDN_TEXT"),
	
	ME2U_CONFIRMATION_TEXT("ME2U_CONFIRMATION_TEXT"),
		
	FAF_SAME_MSISDN_CHECK("FAF_SAME_MSISDN_CHECK"),
	
	ME2U_CONFIRMATION_VALID_INPUTS("ME2U_CONFIRMATION_VALID_INPUTS"),
	
	ONE_KWACHA_IN_NGWEE("ONE_KWACHA_IN_NGWEE"),
	
	ONE_CFA_IN_FRANC("ONE_CFA_IN_FRANC"),
	
	Me2U_DATA2SHARE_SUBSCRIBER_DA("Me2U_DATA2SHARE_SUBSCRIBER_DA"),
	
	Me2U_DATA2SHARE_AMOUNT_CONVERSION_FACTOR("Me2U_DATA2SHARE_AMOUNT_CONVERSION_FACTOR"),
	
	Me2U_DATA2SHARE_EXCLUDED_OFFERID("Me2U_DATA2SHARE_EXCLUDED_OFFERID"),
	
	TIME2SHARE_DAILY_MAX_UA_ID("TIME2SHARE_DAILY_MAX_UA_ID"),
	
	TIME2SHARE_MONTHLY_MAX_UA_ID("TIME2SHARE_MONTHLY_MAX_UA_ID"),
	
	FAF_MAX_ONNET("FAF_MAX_ONNET"),
	
	FAF_MAX_OFFNET("FAF_MAX_OFFNET"),
	
	FAF_MAX_INTERNATIONAL("FAF_MAX_INTERNATIONAL"), 
	
	FAF_MODIFY_MAX_ONNET("FAF_MODIFY_MAX_ONNET"),
	
	FAF_MODIFY_MAX_OFFNET("FAF_MODIFY_MAX_OFFNET"),
	
	FAF_MODIFY_MAX_INTERNATIONAL("FAF_MODIFY_MAX_INTERNATIONAL"),
	
	FAF_SERVICE_CLASS("FAF_SERVICE_CLASS"),
	
	ME2U_DATA2SHARE_OFFERID("ME2U_DATA2SHARE_OFFERID"),ROLLBACK_RESPONSE_CODE("ROLLBACK_RESPONSE_CODE"),
	
	EVDS_ROLLBACK_USERID("EVDS_ROLLBACK_USERID"),
	
	EVDS_ROLLBACK_PASSWORD("EVDS_ROLLBACK_PASSWORD"),
	
	REDIRECT_TO_MAIN_MENU_ON_INCORRECT_USSD("REDIRECT_TO_MAIN_MENU_ON_INCORRECT_USSD"),
	
	ME2U_RECIPIENT_SETTLEMENT_DAS("ME2U_RECIPIENT_SETTLEMENT_DAS"),
	
	NEGWEE_CS_FACTOR("NEGWEE_CS_FACTOR"), 
	
	DATA2SHARE_AMOUNT_NOTIF("DATA2SHARE_AMOUNT_NOTIF"), 
	
	DATA2SHARE_RECEIPIENT_NOTIF("DATA2SHARE_RECEIPIENT_NOTIF"), 
	
	DATA2SHARE_CONFIRM_NOTIF("DATA2SHARE_CONFIRM_NOTIF"), 
	
	KWACHA_NEGWEE_FACTOR("KWACHA_NEGWEE_FACTOR"),
	
	ADD_FAF_FOR_MAGIC_NUMBER("ADD_FAF_FOR_MAGIC_NUMBER"),
	
	IS_FIXED_THREADPOOL_ENABLED("IS_FIXED_THREADPOOL_ENABLED"),
	
	IS_OBJECT_BASED_MODEL("IS_OBJECT_BASED_MODEL"),
	
	/** The Constant PP_REPORT_PARAM_DISPLAY **/
	PP_REPORT_PARAM_DISPLAY("PP_REPORT_PARAM_DISPLAY"),
	
	UA_BASED_NOTIFICATION("UA_BASED_NOTIFICATION"),
 	
	/** SHARED_BONUS_BUNDLE_ADD_CONSUMER_CONFIRMATION_TEXT **/
    SHARED_BONUS_BUNDLE_ADD_CONSUMER_CONFIRMATION_TEXT("SHARED_BONUS_BUNDLE_ADD_CONSUMER_CONF_TEXT"),
    
    /** SHARED_BONUS_BUNDLE_AMOUNT_INPUT_TEXT **/
    SHARED_BONUS_BUNDLE_AMOUNT_INPUT_TEXT("SHARED_BONUS_BUNDLE_AMOUNT_INPUT_TEXT"),
    
    /** SHARED_BONUS_BUNDLE_UC_ID **/
    SHARED_BONUS_BUNDLE_PROVIDER_UC_ID("SHARED_BONUS_BUNDLE_PROVIDER_UC_ID"),
    
    /** SHARED_BONUS_BUNDLE_UT_ID **/
    SHARED_BONUS_BUNDLE_PROVIDER_UT_ID("SHARED_BONUS_BUNDLE_PROVIDER_UT_ID"),
    
    /** SHARED_BONUS_BUNDLE_CONSUMER_UC_ID **/
    SHARED_BONUS_BUNDLE_CONSUMER_UC_ID("SHARED_BONUS_BUNDLE_CONSUMER_UC_ID"),
    
    /** SHARED_BONUS_BUNDLE_CONSUMER_UT_ID **/
    SHARED_BONUS_BUNDLE_CONSUMER_UT_ID("SHARED_BONUS_BUNDLE_CONSUMER_UT_ID"),
    
    /** SHARED_BONUS_BUNDLE_DA_ID **/
    SHARED_BONUS_BUNDLE_DA_ID("SHARED_BONUS_BUNDLE_DA_ID"),
    
    /** SHARED_BONUS_BUNDLE_AMOUNT_HEADER_TEXT **/
    SHARED_BONUS_BUNDLE_AMOUNT_HEADER_TEXT("SHARED_BONUS_BUNDLE_AMOUNT_HEADER_TEXT"),
    
    /** SHARED_BONUS_BUNDLE_DELETE_CONSUMER_CONFIRMATION_TEXT **/
    SHARED_BONUS_BUNDLE_DELETE_CONSUMER_CONFIRMATION_TEXT("SHARED_BONUS_BUNDLE_DELETE_CONSUMER_CONFIRMATION_TEXT"),
    
    /** SHARED_BONUD_BUNDLE_POSTPAID_NOTIFICATION_TEXT_FOR_CONSUMER_INPUT **/
    SHARED_BONUD_BUNDLE_POSTPAID_NOTI_TEXT_CONSUMER("SHARED_BONUS_BUNDLE_POSTPAID_NOTI_TEXT_CONSUMER"),
    
    /** SHARED_BONUD_BUNDLE_DOUBLE_CONFIRMATION_TEXT **/
    SHARED_BONUD_BUNDLE_ADD_DOUBLE_CONFIRMATION_TEXT("SHARED_BONUS_BUNDLE_ADD_DOUBLE_CONF_TEXT"),
    
    /** SHARED_BONUD_BUNDLE_UPGRADE_CONSUMER_DOUBLE_CONFIRMATION_TEXT **/
    SHARED_BONUD_BUNDLE_UPGRADE_CONSUMER_DOUBLE_CONFIRMATION_TEXT("SHARED_BONUS_BUNDLE_UPGRADE_CONSUMER_CONF_TEXT"),
    
    /** SBB_EXTERNAL_SYSTEM_FULFILLEMENT_LOGICAL_NAME **/
    SBB_EXTERNAL_SYSTEM_FULFILLEMENT_LOGICAL_NAME("SBB_EXTERNAL_SYSTEM_FULFILLEMENT_LOGICAL_NAME"),
    
    /** SHARED_BONUD_BUNDLE_DEL_DOUBLE_CONFIRMATION_TEXT **/
    SHARED_BONUD_BUNDLE_DEL_DOUBLE_CONFIRMATION_TEXT("SHARED_BONUS_BUNDLE_DEL_DOUBLE_CONF_TEXT"),
    
    /** SHARED_BONUD_BUNDLE_MAX_ALLOWED_CONSUMERS **/
    SHARED_BONUD_BUNDLE_MAX_ALLOWED_CONSUMERS("SHARED_BONUS_BUNDLE_MAX_ALLOWED_CONSUMERS"),
    
    /** SHARED_BONUD_BUNDLE_MAX_CONSUMER_TEXT **/
    SHARED_BONUD_BUNDLE_MAX_CONSUMER_TEXT("SHARED_BONUS_BUNDLE_MAX_CONSUMER_TEXT"),
    
    /** SHARED_BONUD_BUNDLE_BALANCE_DAID **/
    SHARED_BONUD_BUNDLE_BALANCE_DAID("SHARED_BONUS_BUNDLE_BALANCE_DAID"),
    
    /** SHARED_BONUD_BUNDLE_DEL_SELF_DOUBLE_CONFIRMATION_TEXT **/
    SHARED_BONUD_BUNDLE_DEL_SELF_DOUBLE_CONFIRM_TEXT("SHARED_BONUD_BUNDLE_DEL_SELF_DOUBLE_CONFIRM_TEXT"),
    
    /** SHARED_BONUS_BUNDLE_DEL_HEADER_TEXT **/
    SHARED_BONUS_BUNDLE_DEL_HEADER_TEXT("SHARED_BONUS_BUNDLE_DEL_HEADER_TEXT"),
    
    /** SHARED_BONUS_BUNDLE_DEL_FOOTER_TEXT **/
    SHARED_BONUS_BUNDLE_DEL_FOOTER_TEXT("SHARED_BONUS_BUNDLE_DEL_FOOTER_TEXT"),
    
    /** SHARED_BONUS_BUNDLE_UPGRADE_HEADER_TEXT **/
    SHARED_BONUS_BUNDLE_UPGRADE_HEADER_TEXT("SHARED_BONUS_BUNDLE_UPGRADE_HEADER_TEXT"),
    
    /** SHARED_BONUS_BUNDLE_UPGRADE_FOOTER_TEXT **/
    SHARED_BONUS_BUNDLE_UPGRADE_FOOTER_TEXT("SHARED_BONUS_BUNDLE_UPGRADE_FOOTER_TEXT"),
    
    /** SHARED_BONUD_BUNDLE_BAL_DIVISION_FACTOR **/
    SHARED_BONUD_BUNDLE_BAL_DIVISION_FACTOR("SHARED_BONUS_BUNDLE_BAL_DIVISION_FACTOR"),
    
    /** SHARED_BONUS_BUNDLE_VIEW_HEADER_TEXT */
    SHARED_BONUS_BUNDLE_VIEW_HEADER_TEXT("SHARED_BONUS_BUNDLE_VIEW_HEADER_TEXT"),

	/** SHARED_BONUS_BUNDLE_VIEW_FOOTER_TEXT */
	SHARED_BONUS_BUNDLE_VIEW_FOOTER_TEXT("SHARED_BONUS_BUNDLE_VIEW_FOOTER_TEXT"),

	BUY_OPTIN_OPTOUT_PRODUCT_VALID_RESPONSE("BUY_OPTIN_OPTOUT_PRODUCT_VALID_RESPONSE"),
	
	CONFIRM_PRODUCT_AUTO_RENEWAL("CONFIRM_PRODUCT_AUTO_RENEWAL"),
	
	// Added for double confirmation cancel notification
	CANCEL_NOTIFICATION_RESPONSE("CANCEL_NOTIFICATION_RESPONSE"),
	
	// Added for CS conversion factor
	CS_CONVERSION_FACTOR("CS_CONVERSION_FACTOR"),
	
	/** NUMBER_RESERVATION **/
	NUMBER_RESERVATION("NUMBER_RESERVATION"),
	
	/** NUMBER_RESERVATION_SELF **/
	NUMBER_RESERVATION_SELF("NUMBER_RESERVATION_SELF"),
	
	/** NUMBER_RESERVATION_FOR_SOMEONE **/	
	NUMBER_RESERVATION_FOR_SOMEONE("NUMBER_RESERVATION_FOR_SOMEONE"),
	
	/** NUMBER_RESERVATION_ALTERNATE_NUMBER **/
	NUMBER_RESERVATION_ALTERNATE_NUMBER("NUMBER_RESERVATION_ALTERNATE_NUMBER"),
	
	/** NUMBER_RESERVATION_ALTERNATE_NUMBER_CONFIRM **/
	NUMBER_RESERVATION_ALTERNATE_NUMBER_CONFIRM("NUMBER_RESERVATION_ALTERNATE_NUMBER_CONFIRM"),
	
	/** NUMBER_RESERVATION_NUMBER_TO_RESERVED **/
	NUMBER_RESERVATION_NUMBER_TO_RESERVED("NUMBER_RESERVATION_NUMBER_TO_RESERVED"),
	
	/** NUMBER_RESERVATION_NUMBER_TO_RESERVED_CONFIRM **/
	NUMBER_RESERVATION_NUMBER_TO_RESERVED_CONFIRM("NUMBER_RESERVATION_NUMBER_TO_RESERVED_CONFIRM"),
	
	TYPE_FAF_OR_MAGIC_NUMBER("TYPE_FAF_OR_MAGIC_NUMBER"),
	
	ADD_MAGIC_NUMBER("ADD_MAGIC_NUMBER"),
	/** NUMBER_RESERVATION_NUMBER_TO_RESERVED_CONFIRM_SUGGESTION **/
    NUMBER_RESERVATION_NUMBER_TO_RESERVED_CONFIRM_SUGGESTION("NUMBER_RESERVATION_NUMBER_TO_RESERVED_CONFIRM_SUGGESTION"),
    /** NUMBER_RESERVATION_NUMBER_TO_RESERVED_SUGGESTION **/
    NUMBER_RESERVATION_NUMBER_TO_RESERVED_SUGGESTION("NUMBER_RESERVATION_NUMBER_TO_RESERVED_SUGGESTION"),
    /** NUMBER_RESERVATION_ALTERNATE_NUMBER_SUGGESTION **/
    NUMBER_RESERVATION_ALTERNATE_NUMBER_SUGGESTION("NUMBER_RESERVATION_ALTERNATE_NUMBER_SUGGESTION"),
    /** NUMBER_RESERVATION_ALTERNATE_NUMBER_SUGGESTION **/
    NUMBER_RESERVATION_ERROR_SUGGESTION("NUMBER_RESERVATION_ERROR_SUGGESTION"),
    
	/** DEFAULT_NOTIFICATION : This is default notification that would be sent in case of no DA **/
	DEFAULT_NOTIFICATION("DEFAULT_NOTIFICATION"),
	/** ACTIVATION_ENDATE_INTERVAL for Magic No **/

    OPERATOR_ID_DELIMITER("OPERATOR_ID_DELIMITER"),

	ACTIVATION_ENDDATE_INTERVAL("ACTIVATION_ENDDATE_INTERVAL"), 
	
	ECW_MENU_REDIRECT_SHORT_CODE("ECW_MENU_REDIRECT_SHORT_CODE"),
	
	DECIMAL_FORMAT_BALANCE_ENQUIRY("DECIMAL_FORMAT_BALANCE_ENQUIRY"),
	
	MM_CONTEXT_PATH_DEBIT("MM_CONTEXT_PATH_DEBIT"),
	
	MM_CONTEXT_PATH_REFUND("MM_CONTEXT_PATH_REFUND"),
	
	INVALID_EMAIL_ID_TEXT("INVALID_EMAILID_TEXT"),
	
	ALTERNATE_NUMBER_CONFORM_INVALID_TEXT("ALTERNATE_NUMBER_CONFORM_INVALID_TEXT"),
	
	ALTERNATE_EMAIL_ID_CONFORM_INVALID_TEXT("ALTERNATE_EMAIL_ID_CONFORM_INVALID_TEXT"),
	
	/** AUTO_RENEWAL_CONFIRMATION. **/
	AUTO_RENEWAL_CONFIRMATION("AUTO_RENEWAL_CONFIRMATION"),
	
	AUTO_RENEWAL_CONFIRMATION_TEXT_SMS("AUTO_RENEWAL_CONFIRMATION_TEXT_SMS"),

	TIME_2_SHARE_CONFIRMATION_NOTIFICATION("TIME_2_SHARE_CONFIRMATION_NOTIFICATION"),
	
	GHC_CONVERSION_FACTOR("GHC_CONVERSION_FACTOR"),
	
	TIME_2_SHARE_DA_ACCOUNT_FROM("TIME_2_SHARE_DA_ACCOUNT_FROM"),
	
	TIME_2_SHARE_DA_ACCOUNT_TO("TIME_2_SHARE_DA_ACCOUNT_TO"),
	
	CURRENCY("CURRENCY"),
	
	ME2U_CANCLE_NOTICATION("ME2U_CANCLE_NOTICATION"),
	
	AUTO_RENEWAL_CONFIRMATION_TEXT("AUTO_RENEWAL_CONFIRMATION_TEXT"),
	
	ME2U_ENTER_PIN_TEXT("ME2U_ENTER_PIN_TEXT"),
	
	ME2U_PIN_LENGTH("ME2U_PIN_LENGTH"),
	
	ME2U_PIN_INVALID_TEXT("ME2U_PIN_INVALID_TEXT"),
	
	ME2U_CREATE_PIN_TEXT("ME2U_CREATE_PIN_TEXT"),
	
	DATA2SHARE_ENTER_BENEFICIARY_MSISDN_TEXT("DATA2SHARE_ENTER_BENEFICIARY_MSISDN_TEXT"),
	
	DATA2SHARE_ENTER_BENEFICIARY_MSISDN_INVALID_TEXT("DATA2SHARE_ENTER_BENEFICIARY_MSISDN_INVALID_TEXT"),
	
	DATA2SHARE_ENTER_BENEFICIARY_MSISDN_CONFORM_TEXT("DATA2SHARE_ENTER_BENEFICIARY_MSISDN_CONFORM_TEXT"),
	
	DATA2SHARE_ENTER_BENEFICIARY_CONFORM_INVALID_TEXT("DATA2SHARE_ENTER_BENEFICIARY_CONFORM_INVALID_TEXT"),
	
	DATA2SHARE_CONFIRMATION_VALID_INPUT("DATA2SHARE_CONFIRMATION_VALID_INPUT"),
	
	DATA2SHARE_DA_ACCOUNT_FROM("DATA2SHARE_DA_ACCOUNT_FROM"),
	
	DATA2SHARE_DA_ACCOUNT_TO("DATA2SHARE_DA_ACCOUNT_TO"),
	
	DATA2SHARE_CONFIRMATION_NOTIFICATION("DATA2SHARE_CONFIRMATION_NOTIFICATION"),
	
	DATA2SHARE_CANCELLATION_VALID_INPUT("DATA2SHARE_CANCELLATION_VALID_INPUT"),
	
	DATA2SHARE_CANCEL_TEXT("DATA2SHARE_CANCEL_TEXT"),
	
	DATA2SHARE_SKIP_CHARGING("DATA2SHARE_SKIP_CHARGING"),
	
	TIME2SHARE_CANCELLATION_VALID_INPUT("TIME2SHARE_CANCELLATION_VALID_INPUT"),
	
	ROLLBACK_RETRY_RESPONSE_CODE("ROLLBACK_RETRY_RESPONSE_CODE"),
	
	ROLLBACK_RETRY_INTERVAL("ROLLBACK_RETRY_INTERVAL"),
	
	ROLLBACK_RETRY_COUNT("ROLLBACK_RETRY_COUNT"),
	
	AUTO_RENEWAL_UA_ID("AUTO_RENEWAL_UA_ID"),
	
	MM_CONTEXT_PATH_GET_TRANSACTION("MM_CONTEXT_PATH_GET_TRANSACTION"),
	
	RETURN_TO_PREVIOUS_MENU_ON_EXCEPTION("RETURN_TO_PREVIOUS_MENU_ON_EXCEPTION"),
	
	ASYNC_MM_DEBIT_PROCESSING("ASYNC_MM_DEBIT_PROCESSING"),
	
	MM_DEBIT_PROCESSING_DELAY("MM_DEBIT_PROCESSING_DELAY"),
	/** The Constant BUY_OTHER_INVALID_MSISDN_TEXT **/
	BUY_OTHER_INVALID_MSISDN_TEXT("BUY_OTHER_INVALID_MSISDN_TEXT")
	;
	


	/**
	 * Instantiates a new configuration key.
	 * 
	 * @param attribute
	 *            the attribute
	 */
	private ConfigurationKey(final String attribute) {
		this.attributeName = attribute;
	}

	/**
	 * Gets the attribute name.
	 * 
	 * @return the attribute name
	 */
	public String getAttributeName() {
		return attributeName;
	}

	/** The attribute name. */
	private String attributeName;

}
